---
name: YAML Linting

jobs:
  lint-yaml:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pipelinecomponents/yamllint
        with:
          args: >-
            yamllint
            --config-file=.config/.yamllint
            .
