---
name: Validate dependencies file

jobs:
  validate-dependencies-file:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: >-
            composer validate
            --check-lock
            --no-plugins
            --no-scripts
            --strict
            --working-dir=solid/
