---
name: PHP Unit Tests

jobs:
  php-unittest:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'  # from 2020-11 to 2022-11 (2023-11)
          - '8.1'  # from 2021-11 to 2023-11 (2025-12)
          - '8.2'  # from 2022-12 to 2024-12 (2026-12)
          - '8.3'  # from 2023-11 to 2025-12 (2027-12)
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          ini-values: error_reporting=E_ALL, display_errors=On
          php-version: ${{ matrix.php }}
      - name: Install and Cache Composer dependencies
        uses: "ramsey/composer-install@v2"
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}'
      - run: bin/phpunit --configuration .config/phpunit.xml.dist
