---
name: PHP Version Compatibility

jobs:
  php-check-version-compatibility:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'  # from 2020-11 to 2022-11 (2023-11)
          - '8.1'  # from 2021-11 to 2023-11 (2025-12)
          - '8.2'  # from 2022-12 to 2024-12 (2026-12)
          - '8.3'  # from 2023-11 to 2025-12 (2027-12)
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pipelinecomponents/php-codesniffer
        with:
          args: >-
            phpcs
            -s
            --extensions=php
            --ignore='*vendor/*'
            --runtime-set testVersion ${{ matrix.php }}
            --standard=PHPCompatibility
            .
